version: '3.8'

services:
  pyspark_clusterizer:
    container_name: pyspark_clusterizer
    build: 
      context: ./pyspark_clusterizer
      dockerfile: Dockerfile
    image: pythondestroyer/pyspark_clusterizer:main
    command: python main.py
    depends_on: 
      - data_mart
    volumes: 
      - ./models/:/app/models

  data_mart: 
    container_name: data_mart
    build:
      context: ./data_mart
      dockerfile: Dockerfile
    image: pythondestroyer/data_mart:main
    shm_size: '8gb'
    command: python api.py
    depends_on: 
      - redis
      - data_producer
    ports: 
      - 8000:8000

  data_producer:
    container_name: data_producer
    build: 
      context: ./data_producer
      dockerfile: Dockerfile
    image: pythondestroyer/data_producer:main
    command: python store_data.py
    volumes: 
      - ./data/:/app/data
    depends_on: 
      - redis

  redis: 
    container_name: redis
    image: redis:alpine3.18
    ports: 
      - 6379:6379
